%YAML 1.0
---

# RISC OS build file executed by https://build.riscos.online/
jobs:
  build:
    env:
      "Sys$Environment": ROBuild
      "BUILD32": 1
      "Alias$AMU": "HostAMU %*0"

    script:
      - echo
      - echo *** Build and run the native tests ***
      - amu -f C/apps/riscos/Makefile aif32.ChaseTest
      - aif32.ChaseTest

      - echo
      - echo *** Ensure that we have resources ***
      - copy C.apps.riscos.Resources Resources ~CFVR
      - copy C.apps.riscos.VersionNum VersionNum ~CFVR

      - echo
      - echo *** Build the application bundle ***
      - amu -f C/apps/riscos/Makefile install INSTDIR=Install

      - echo
      - echo *** SUCCESS ***

    artifacts:
      - path: Install
