/**
 * Stage6Data.c
 *
 * This file is part of "Chase H.Q. in C".
 *
 * This project recreates the ZX Spectrum version of the chase-and-smash game
 * "Chase H.Q." in portable C code. It is free software provided without
 * warranty in the interests of education and software preservation.
 *
 * The arcade original was created by Taito Corporation in 1988. It was then
 * ported to the ZX Spectrum by Ocean Software Limited and released in 1989.
 *
 * The original game and design is copyright (c) 1988 Taito Corporation.
 * The ZX Spectrum version is copyright (c) 1989 Ocean Software Limited.
 * The recreated version is copyright (c) 2023-2026 David Thomas.
 */

#include <stddef.h>

#include "C99/Types.h"
#include "ZXSpectrum/Pixels.h"
#include "ZXSpectrum/Spectrum.h"

#include "ChaseHQ/Engine/Types.h"
#include "CommonData.h"

#include "Stage6Data.h"

/* Z80 addresses of the map sections, as referenced by the map
 * GOTO/SPLIT commands and stage6_map_goto_table[]. */
#define STAGE6_MAP_START_CURVATURE_ADDR (0xC65C)
#define STAGE6_MAP_START_HEIGHT_ADDR    (0xC65D)
#define STAGE6_MAP_START_LANES_ADDR     (0xC65E)
#define STAGE6_MAP_START_HAZARDS_ADDR   (0xC65F)
#define STAGE6_MAP_START_LEFTOBJS_ADDR  (0xC660)
#define STAGE6_MAP_START_RIGHTOBJS_ADDR (0xC661)

/* ----------------------------------------------------------------------- */

/* Stage 6 object type macros */

/* ----------------------------------------------------------------------- */

/* Forward declarations */

static const u8 stage6_perp_description[7];
static const char *stage6_chatter_strings[4];
static const u8 stage6_arrest_messages[83];
static const hittable_t stage6_hittable_objects[2];
static const obj_t stage6_right_hand_objects[7];
static const obj_t stage6_left_hand_objects[7];

/* Generated by C/scripts/stage_compile.py from C/maps/stage6.map.
 * Sizes must match the definitions below. */
static const u8 stage6_map_start_curvature[28];
static const u8 stage6_map_start_height[29];
static const u8 stage6_map_start_lanes[36];
static const u8 stage6_map_start_hazards[37];
static const u8 stage6_map_start_leftobjs[13];
static const u8 stage6_map_start_rightobjs[13];

static const pixel_t stage6_perp_face[180];
static const bitmap_t stage6_veh3[6];
static const bitmap_t stage6_veh2[6];
static const bitmap_t stage6_veh1[6];

static const bitmap_t stage6_lods_D620[6];

static const pixel_t stage6_bitmap_D64A[181];

/* ----------------------------------------------------------------------- */

/**
 * stage6
 *
 * Conv: additional test stage, not present in the original game (see
 * Stages.c, CHQ_ENABLE_TEST_STAGE). Road layout and graphics tables below
 * carry their own Z80 addresses from bank 4 where they are reused from;
 * the perp description and chatter text are placeholder content authored
 * for this port with no originating address.
 */
// clang-format off
const stage_t stage6 = {
  {
    XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
    X_XXXXXX, X_X___XX, XX______, X_X_X_X_, X_X_XXX_, X_X_X___, X___XXX_, X_X_X_X_, X_X_X_X_, XXXXXXX_,
    XXXXX___, _X_X_X_X, _XX__X__, _____X_X, _X_X_XX_, _X______, _____X__, _X_X_X__, XX______, _X_XXX_X,
    XXX_____, X_X_X_XX, X_____X_, X_X_X_X_, X_X_X_XX, X_X_X_X_, X_X_____, __X_X_X_, _XX___X_, X_XXX_XX,
    X_______, ___X_X_X, XX__X___, ___X_X__, _X_X_X_X, XX_X____, ________, ___X___X, __XX____, ___XXXXX,
    __X_____, X_X_XXXX, _____XX_, X_X_X_X_, XXX_XXX_, XXXXX_X_, X_X_X_X_, X___X___, XX_XX___, X_X_XXXX,
    ________, _X_X_X_X, X_______, _X_X_X_X, _X_X_X_X, _X_XXX_X, _X___X_X, ________, __XXXX__, _X_XXXX_,
    X_____X_, X_X_XXX_, __X_X_X_, X_X___XX, XXX_XXXX, X_X_XXX_, X_X_X_X_, X_X___X_, ___XXXX_, __XXXX__,
    ________, ___XX_XX, __XXX__X, ___X_X_X, _X_XXX_X, _X_XXXXX, ___X___X, _X_X_X__, __X____X, _X_XXX_X,
    ____X_X_, XXX_XX__, ___X__X_, __X_XXXX, XXXXXXXX, XXXXX_X_, X___X_XX, X_X_X_X_, X_X_X___, X_XXX_X_,
    ________, _X_XX_XX, _X___X__, _X_X_X_X, XX_XXXXX, _X_X_X__, ________, XX______, _X______, _XXX_X_X,
    ______X_, X_X_XX__, __X_X___, X_XXX_XX, X_XXXXXX, XXXXX_X_, X___X__X, XXX_X___, X_X_X_X_, X_X___X_,
    ________, _X_XXXX_, _X______, _X_X_XXX, XXX_XXXX, _X_X____, X__X___X, XXXX____, _X_XX___, ________,
    ____X_X_, XXXXX_XX, X_X_____, X_X_XXX_, XXXXXX_X, X_X_X_X_, XX_X__XX, XXXXXX__, ____XX__, X_X_X_X_,
    __X____X, XXXX_X_X, _X__X__X, _X_XXX_X, X_XXXXXX, _X_X_X__, XX_X_XXX, XX_XXXXX, __X__XXX, _X___X__,
    ____X_X_, XXXXXXX_, X_X_____, __XXXXXX, XXXXX___, XXX_X_X_, XXX__XXX, XXXXX_X_, XX__X_X_, X_X_X_X_,
    __X__X_X, XX____XX, XX_X___X, _XXX_XXX, XXX_____, ___X_XX_, _XX_XXXX, _X_XXXXX, XXXXX__X, XX_X_X_X,
    X_XXXXXX, X_______, __XXXX__, XX_XXXXX, ________, ____XXXX, ____XXXX, XXXXX___, _____XXX, XXX_XXX_,
    _XXXXXX_, ________, ____XXX_, _XXXXX__, ________, ______XX, X__XXX_X, XX______, ________, _XXXXXXX,
    XXXXX___, ________, ______XX, XXXXX___, ________, _______X, XXX_XXXX, ________, ________, __XXX_XX,
    XXX_____, ________, ________, XXX_____, ________, ________, _XXXXX__, ________, ________, _______X,
    ________, ________, ________, ________, ________, ________, __XX____, ________, ________, ________,
    ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
    ________, ________, ________, ________, ________, ________, ________, ________, ________, ________,
  },
  &stage6_perp_face[FACEBITMAPBYTES],
  NULL,
  attribute_BRIGHT_BLACK_OVER_GREEN * 0x0101,
  &stage6_hittable_objects[0],
  &stage6_right_hand_objects[-1].arg,
  &stage6_right_hand_objects[-1],
  &stage6_right_hand_objects[2],
  &stage6_left_hand_objects[-1].arg,
  &stage6_left_hand_objects[-1],
  &stage6_left_hand_objects[2],
  &stage6_perp_description[0],
  &stage6_arrest_messages[0],
  { NULL, NULL },

  NULL,  /* bitmaps_stones */
  NULL,  /* bitmaps_dust */
  &stage6_veh3[0],  /* bitmaps_perp_car */
  {
    &stage6_veh1[0],
    &stage6_veh2[0],
    &stage6_veh1[0],
    &stage6_veh3[0]
  },  /* bitmaps_vehicles */

  /* $C11A difficulty */
  20,  /* car_spawn_delay */
  40,  /* perp_lane_change_base */
  40,  /* perp_approach_base */

  /* $C11D setupdata */
  {
    158,
    &stage6_map_start_curvature[-1],
    &stage6_map_start_height[-1],
    &stage6_map_start_lanes[-1],
    &stage6_map_start_rightobjs[-1],
    &stage6_map_start_leftobjs[-1],
    &stage6_map_start_hazards[-1],
  },

  /* $C12B attractdata */
  {
    234,
    &stage6_map_start_curvature[-1],
    &stage6_map_start_height[-1],
    &stage6_map_start_lanes[-1],
    &stage6_map_start_rightobjs[-1],
    &stage6_map_start_leftobjs[-1],
    &stage6_map_start_hazards[-1],
  },

  stage6_chatter_strings
};

/* ----------------------------------------------------------------------- */

/** $C139: stage6_perp_description */
static const u8 stage6_perp_description[7] = {
  CHATTERCHR_NANCY,
  CHATTERSTR_PERP_DESC_1,
  CHATTERCMD_PAUSE,
  CHATTERBLK_HEROES_ACKNOWLEDGE
};

/**
 * stage6_chatter_strings
 *
 * Conv: placeholder text for the test stage; no originating Z80 address.
 */
static const char *stage6_chatter_strings[4] = {
  "THIS IS A TEST LEVEL\xAE",
};

/* ----------------------------------------------------------------------- */

/**
 * $C1E6: stage6_arrest_messages
 */
static const u8 stage6_arrest_messages[83] = {
  6,  // initial delay

  6,  // delay
  DRAWCHARSTYLE_SINGLE,
  0,  // attribute
  CHQBACKBUF(0xF802),
  ZXATTRS(0x5922),
  'O', 'K', '!', ' ', 'Y', 'O', 'U', ' ', 'A', 'R', 'E', ' ', 'U', 'N', 'D', 'E', 'R', ' ', 'A', 'R', 'R', 'E', 'S', 'T' | EOS,

  TRANSITIONCONTROL_FILL_ATTRIBUTES,
  DRAWOVERLAY_STOP
};

/* ----------------------------------------------------------------------- */

/** $C239: stage6_hittable_objects */
static const hittable_t stage6_hittable_objects[2] = {
  { 32, &stage6_lods_D620[0] },
  { 32, &stage6_lods_D620[0] },
};

/** $C23F: stage6_right_hand_objects */
static const obj_t stage6_right_hand_objects[7] = {
  { 111, 41, 80, &tunnellight, draw_tunnel_light_right },
};

/** $C270: stage6_left_hand_objects */
static const obj_t stage6_left_hand_objects[7] = {
  { 126, 188, 80, &tunnellight, draw_tunnel_light_left },
};

/* ----------------------------------------------------------------------- */

/** $C65C: stage6_map_start_curvature */
static const u8 stage6_map_start_curvature[28] = {
  MAP_CURVE_STRAIGHT(15),
  MAP_CURVE_STRAIGHT(5),
  MAP_CURVE_RIGHT(10),
  MAP_CURVE_RIGHT_HARD(15),
  MAP_CURVE_RIGHT_HARD(1),
  MAP_CURVE_RIGHT(12),
  MAP_CURVE_STRAIGHT(2),
  MAP_CURVE_LEFT(14),
  MAP_CURVE_LEFT_HARD(10),
  MAP_CURVE_LEFT(15),
  MAP_CURVE_LEFT(1),
  MAP_CURVE_STRAIGHT(14),
  MAP_CURVE_RIGHT(2),
  MAP_CURVE_RIGHT_HARD(15),
  MAP_CURVE_RIGHT_HARD(5),
  MAP_CURVE_STRAIGHT(12),
  MAP_CURVE_LEFT_HARD(12),
  MAP_CURVE_LEFT(8),
  MAP_CURVE_STRAIGHT(10),
  MAP_CURVE_RIGHT(8),
  MAP_CURVE_STRAIGHT(14),
  MAP_CURVE_RIGHT(8),
  MAP_CURVE_STRAIGHT(15),
  MAP_CURVE_STRAIGHT(11),
  MAP_CMD_GOTO(STAGE6_MAP_START_CURVATURE_ADDR)
};

/** $C65D: stage6_map_start_height */
static const u8 stage6_map_start_height[29] = {
  MAP_HEIGHT_LEVEL(15),
  MAP_HEIGHT_LEVEL(15),
  MAP_HEIGHT_UP3(15),
  MAP_HEIGHT_UP3(1),
  MAP_HEIGHT_UP5(12),
  MAP_HEIGHT_UP1(2),
  MAP_HEIGHT_LEVEL(14),
  MAP_HEIGHT_DOWN3(10),
  MAP_HEIGHT_DOWN1(15),
  MAP_HEIGHT_DOWN1(1),
  MAP_HEIGHT_LEVEL(2),
  MAP_HEIGHT_UP3(12),
  MAP_HEIGHT_UP1(2),
  MAP_HEIGHT_LEVEL(15),
  MAP_HEIGHT_LEVEL(5),
  MAP_HEIGHT_DOWN5(10),
  MAP_HEIGHT_DOWN3(2),
  MAP_HEIGHT_LEVEL(15),
  MAP_HEIGHT_LEVEL(5),
  MAP_HEIGHT_UP3(10),
  MAP_HEIGHT_LEVEL(8),
  MAP_HEIGHT_DOWN1(14),
  MAP_HEIGHT_LEVEL(15),
  MAP_HEIGHT_LEVEL(15),
  MAP_HEIGHT_LEVEL(4),
  MAP_CMD_GOTO(STAGE6_MAP_START_HEIGHT_ADDR)
};

/** $C65E: stage6_map_start_lanes */
static const u8 stage6_map_start_lanes[36] = {
  MAP_LANES_4(58),
  MAP_LANES_4TO3R(2),
  MAP_LANES_3R(22),
  MAP_LANES_3RTO2R(2),
  MAP_LANES_2R(16),
  MAP_LANES_2RTO3R(2),
  MAP_LANES_3R(12),
  MAP_LANES_3RTO4(2),
  MAP_LANES_4(30),
  MAP_LANES_4TO3L(2),
  MAP_LANES_3L(12),
  MAP_LANES_TUNNEL_ENTRY(24),
  MAP_LANES_TUNNEL_EXIT(2),
  MAP_LANES_3L(28),
  MAP_LANES_3LTO4(2),
  MAP_LANES_4(18),
  MAP_CMD_GOTO(STAGE6_MAP_START_LANES_ADDR)
};

/** $C65F: stage6_map_start_hazards */
static const u8 stage6_map_start_hazards[37] = {
  MAP_CMD_START_CARS,
  MAP_HAZARD_WAIT(37),
  MAP_CMD_START_BARRIERS_R,
  MAP_HAZARD_WAIT(5),
  MAP_CMD_STOP_BARRIERS,
  MAP_HAZARD_WAIT(9),
  MAP_CMD_START_OBSTACLE_L,
  MAP_HAZARD_WAIT(6),
  MAP_CMD_STOP_BARRIERS,
  MAP_HAZARD_WAIT(1),
  MAP_CMD_ARROW_R,
  MAP_HAZARD_WAIT(10),
  MAP_CMD_ARROW_OFF,
  MAP_HAZARD_WAIT(6),
  MAP_CMD_STOP_CARS,
  MAP_HAZARD_WAIT(19),
  MAP_CMD_START_CARS,
  MAP_HAZARD_WAIT(7),
  MAP_CMD_START_TWO_OBSTACLES,
  MAP_HAZARD_WAIT(4),
  MAP_CMD_STOP_BARRIERS,
  MAP_HAZARD_WAIT(13),
  MAP_CMD_GOTO(STAGE6_MAP_START_HAZARDS_ADDR)
};

/** $C660: stage6_map_start_leftobjs */
static const u8 stage6_map_start_leftobjs[13] = {
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(5),
  MAP_OBJ_TUNNEL_LIGHT(13),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(9),
  MAP_CMD_GOTO(STAGE6_MAP_START_LEFTOBJS_ADDR)
};

/** $C661: stage6_map_start_rightobjs */
static const u8 stage6_map_start_rightobjs[13] = {
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(5),
  MAP_OBJ_TUNNEL_LIGHT(13),
  MAP_OBJ_NONE(15),
  MAP_OBJ_NONE(9),
  MAP_CMD_GOTO(STAGE6_MAP_START_RIGHTOBJS_ADDR)
};

/**
 * $C82E: stage6_perp_face
 */
static const pixel_t stage6_perp_face[FACEBYTES] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, X_XXXXX_, XXX_XXX_, X_X_X__X,
  XXXXXXXX, X_XX_XX_, XX__XX_X, XXXX_X_X,
  XXXXXXXX, _XXXXX_X, XX_X_XXX, _XX__X_X,
  XXXXXXXX, XXX__XX_, _XXXX_X_, _XXXX__X,
  XXXXXXXX, XX______, _______X, XXX_XX_X,
  XXXXXXXX, X_X_____, ________, XXXXXX_X,
  XXXXXXXX, XX______, _______X, _XXXXX_X,
  XXXXXXXX, X_______, ________, X_XXX__X,
  XXXXXXXX, XX______, ________, _XXXX__X,
  XXXXXXXX, X_X_____, ________, X_XXX__X,
  XXXXXXXX, XX______, __XXXX__, _XXXX__X,
  XXXXXXXX, XXXX____, XXXXXXX_, _XXX___X,
  XXXXXXXX, XXXX____, XXX____X, _XXX___X,
  XXXXXXX_, ___XX___, XXXXXX__, _XXXX__X,
  XXXXXX__, XXXXXX__, XX_XX_X_, __XX_X_X,
  XXXXXXXX, XX_XXX__, _X______, ___X_X_X,
  XXXXXX_X, __XXX___, _XXX____, __XX_X_X,
  XXXXXX__, XX_XXX__, _XX_____, ___X_X_X,
  X_XXX___, __XXX___, ___X____, __XX_X_X,
  X_XXXX_X, _XXX____, ___XX___, ___XX__X,
  X_XXXXX_, X_XXXX__, _XXXXX__, ___XX__X,
  XXXXXXXX, XXXXXXXX, XX__XX__, ___X___X,
  X_XXXXXX, XXXXXXX_, _____XX_, ___X___X,
  X_XXXXXX, XXXXXX_X, _____XX_, X__X___X,
  X__XXXXX, XXXXXXXX, XXX___X_, X_X____X,
  X__XXXXX, XXXXXX__, ___XX_X_, X_X____X,
  X__XXXXX, XXXXX___, ______X_, __X____X,
  X__XXXXX, XXXXXXXX, XXX_____, __X____X,
  X___XXXX, XXXX_XXX, X_XX____, __X____X,
  X___XXXX, XXX_X___, ________, __X____X,
  X____XXX, XXXX_X__, ________, __XX___X,
  X____XXX, XXXXX___, _____X__, _XXXX__X,
  X___XXXX, XXXXXX_X, _X_XX___, _X_XXX_X,
  X__XXXXX, XXXXXXXX, XXX_____, X_XXXX_X,
  X_XXXXX_, XXXXXXX_, X_____XX, X_XXXXXX,
  X_XX_XXX, XXXXXX_X, _X_XXX_X, X_X_XXXX,
  XXXXXXXX, _XXXXXXX, XXX____X, _XXXXXXX,
  XXXXXX_X, X_XXX___, ______X_, XXXXXX_X,
  XXXX_XXX, XXXXXXXX, XXXXXXXX, XX_XXXXX,

  attribute_BRIGHT_BLACK_OVER_YELLOW, attribute_BLACK_OVER_YELLOW, attribute_BRIGHT_BLACK_OVER_YELLOW, attribute_BRIGHT_BLACK_OVER_CYAN,
  attribute_BLACK_OVER_YELLOW, attribute_BLACK_OVER_YELLOW, attribute_BRIGHT_BLACK_OVER_YELLOW, attribute_BLACK_OVER_WHITE,
  attribute_BLACK_OVER_YELLOW, attribute_BLACK_OVER_YELLOW, attribute_BRIGHT_BLACK_OVER_YELLOW, attribute_BLACK_OVER_WHITE,
  attribute_BRIGHT_BLACK_OVER_CYAN, attribute_BRIGHT_BLACK_OVER_YELLOW, attribute_BRIGHT_BLACK_OVER_YELLOW, attribute_BRIGHT_BLACK_OVER_CYAN,
  attribute_BRIGHT_BLACK_OVER_CYAN, attribute_BLACK_OVER_WHITE, attribute_BRIGHT_BLACK_OVER_YELLOW, attribute_BRIGHT_BLACK_OVER_WHITE,
};

/* ----------------------------------------------------------------------- */

/** $C8E2: stage6_veh3 - Conv: Deduped to CommonData.c (shared with stage 1) */
static const bitmap_t stage6_veh3[6] = {
#ifdef CHQ_ENABLE_MASKED_VEHICLES
  { 6, BITMAPFLAG_MASKED, 30, &bitmap_lambo_1_masked[0], &bitmap_lambo_1_masked[0] },  // [0]
  { 5, BITMAPFLAG_MASKED, 22, &bitmap_lambo_2_masked[0], &bitmap_lambo_2_masked[0] },  // [1]
  { 3, BITMAPFLAG_MASKED, 15, &bitmap_lambo_3_masked[0], &bitmap_lambo_3_masked[0] },  // [2]
  { 3, BITMAPFLAG_MASKED, 15, &bitmap_lambo_3_masked[0], &bitmap_lambo_3_masked[0] },  // [3]
#else
  { 6, BITMAPFLAG_DEFAULT, 30, &bitmap_lambo_1[0], &bitmap_lambo_1[0] },  // [0]
  { 5, BITMAPFLAG_DEFAULT, 22, &bitmap_lambo_2[0], &bitmap_lambo_2[0] },  // [1]
  { 3, BITMAPFLAG_DEFAULT, 15, &bitmap_lambo_3[0], &bitmap_lambo_3[0] },  // [2]
  { 3, BITMAPFLAG_DEFAULT, 15, &bitmap_lambo_3[0], &bitmap_lambo_3[0] },  // [3]
#endif
  { 3, BITMAPFLAG_MASKED, 8, &bitmap_lambo_4[0], &bitmap_lambo_4[0] },  // [4]
  { 3, BITMAPFLAG_MASKED, 8, &bitmap_lambo_4[0], &bitmap_lambo_4s[0] },  // [5]
};

/** $C90C: stage6_veh2 - Conv: Deduped to CommonData.c (shared with stage 1) */
static const bitmap_t stage6_veh2[6] = {
#ifdef CHQ_ENABLE_MASKED_VEHICLES
  { 6, BITMAPFLAG_MASKED, 39, &bitmap_truck_1_masked[0], &bitmap_truck_1_masked[0] },  // [0]
  { 5, BITMAPFLAG_MASKED, 29, &bitmap_truck_2_masked[0], &bitmap_truck_2_masked[0] },  // [1]
  { 3, BITMAPFLAG_MASKED, 20, &bitmap_truck_3_masked[0], &bitmap_truck_3_masked[0] },  // [2]
  { 3, BITMAPFLAG_MASKED, 20, &bitmap_truck_3_masked[0], &bitmap_truck_3_masked[0] },  // [3]
#else
  { 6, BITMAPFLAG_DEFAULT, 39, &bitmap_truck_1[0], &bitmap_truck_1[0] },  // [0]
  { 5, BITMAPFLAG_DEFAULT, 29, &bitmap_truck_2[0], &bitmap_truck_2[0] },  // [1]
  { 3, BITMAPFLAG_DEFAULT, 20, &bitmap_truck_3[0], &bitmap_truck_3[0] },  // [2]
  { 3, BITMAPFLAG_DEFAULT, 20, &bitmap_truck_3[0], &bitmap_truck_3[0] },  // [3]
#endif
  { 2, BITMAPFLAG_MASKED, 12, &bitmap_truck_4[0], &bitmap_truck_4s[0] },  // [4]
  { 2, BITMAPFLAG_MASKED, 12, &bitmap_truck_4[0], &bitmap_truck_4s[0] },  // [5]
};

/** $C936: stage6_veh1 - Conv: Deduped to CommonData.c (shared with stage 3/5) */
static const bitmap_t stage6_veh1[6] = {
#ifdef CHQ_ENABLE_MASKED_VEHICLES
  { 6, BITMAPFLAG_MASKED, 30, &bitmap_C95E_masked[0], &bitmap_C95E_masked[0] },  // [0]
  { 4, BITMAPFLAG_MASKED, 20, &bitmap_CA12_masked[0], &bitmap_CA12_masked[0] },  // [1]
  { 3, BITMAPFLAG_MASKED, 13, &bitmap_CA62_masked[0], &bitmap_CA62_masked[0] },  // [2]
  { 3, BITMAPFLAG_MASKED, 13, &bitmap_CA62_masked[0], &bitmap_CA62_masked[0] },  // [3]
#else
  { 6, BITMAPFLAG_DEFAULT, 30, &bitmap_C95E[0], &bitmap_C95E[0] },  // [0]
  { 4, BITMAPFLAG_DEFAULT, 20, &bitmap_CA12[0], &bitmap_CA12[0] },  // [1]
  { 3, BITMAPFLAG_DEFAULT, 13, &bitmap_CA62[0], &bitmap_CA62[0] },  // [2]
  { 3, BITMAPFLAG_DEFAULT, 13, &bitmap_CA62[0], &bitmap_CA62[0] },  // [3]
#endif
  { 2, BITMAPFLAG_MASKED, 8, &bitmap_CA89[0], &bitmap_CA89[0] },  // [4]
  { 2, BITMAPFLAG_MASKED, 8, &bitmap_CA89[0], &bitmap_CAA9[0] },  // [5]
};

/** $D620: stage6_lods_D620 */
static const bitmap_t stage6_lods_D620[6] = {
  { 4, BITMAPFLAG_DEFAULT, 17, &stage6_bitmap_D64A[0], &stage6_bitmap_D64A[0] },  // [0]
  { 4, BITMAPFLAG_DEFAULT, 17, &stage6_bitmap_D64A[0], &stage6_bitmap_D64A[0] },  // [1]
  { 3, BITMAPFLAG_DEFAULT, 13, &stage6_bitmap_D64A[68], &stage6_bitmap_D64A[68] },  // [2]
  { 2, BITMAPFLAG_DEFAULT, 9, &stage6_bitmap_D64A[107], &stage6_bitmap_D64A[107] },  // [3]
  { 2, BITMAPFLAG_DEFAULT, 9, &stage6_bitmap_D64A[107], &stage6_bitmap_D64A[107] },  // [4]
  { 2, BITMAPFLAG_MASKED, 7, &stage6_bitmap_D64A[125], &stage6_bitmap_D64A[153] },  // [5]
};

/**
 * $D64A: stage6_bitmap_D64A
 */
static const pixel_t stage6_bitmap_D64A[181] = {
  ___XXXXX, XX______, ______XX, XXXXX___, ___XXXX_, _X____XX, XX____XX, _X__X___,
  ____XX_X, __X___XX, _X___XX_, X__X____, ____XXX_, X_X___XX, XX___XXX, _X_X____,
  _____XXX, _X_X__XX, _X__XXX_, X_X_____, _____XX_, X__X_XX_, X_X_XX_X, __X_____,
  ______XX, _X__XXXX, __XXX_X_, _X______, ______XX, X_X_XXX_, X_XXXX_X, _X______,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXX_X, _XXXXXX_, _XXXXXX_, X_XXXXXX,
  XXXXX___, _XXXXX__, __XXXXX_, ___XXXXX, XXXXX___, _XXXXX__, __XXXXX_, ___XXXXX,
  XXXXX___, _XXXXX__, __XXXXX_, ___XXXXX, XXXXX___, _XXXXX__, __XXXXX_, ___XXXXX,
  X_X_X___, _X_X_X__, __X_X_X_, ___X_X_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, ____XXXX, XXXXX___, ________, __XXXXXX, ________, XXXXXX__, __XXX_XX,
  ___XXX__, XX_X_X__, ___XXX_X, X__X_X_X, X_X_X___, ___XX_X_, X_XX_X_X, XX__X___,
  ____XX_X, X_X_X_XX, X__X____, ____XXX_, _XXXXXXX, XX_X____, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_XX, XXXX_XXX, X_X_XXXX, XXXX___X, XXX__XXX, X___XXXX, XXXX___X,
  XXX__XXX, X___XXXX, X__X___X, __X__X__, X___X__X, XXXXXXXX, XXXXXXXX, XXXXXXXX,
  ________, _XXXXXX_, ________, _XXXX___, ___XXXX_, _XX_X__X, X__XX_X_, __XX_X_X,
  X_XX_X__, __XXXX_X, X_XXXX__, XXXXXXXX, XXXXXXXX, XXX__XXX, __XXX__X, X_X__X_X,
  __X_X__X, XXXXXXXX, XXXXXXXX, ______XX, XX______, X__XXXXX, _XX_____, X__XXXXX,
  _XX_____, X___X__X, _XXX_XX_, ___XXXXX, XXX_____, XX______, __XXXXXX, __XXXXXX,
  XX______, ________, XXXXXXXX, ____XXXX, XXXX____, ________, X__XX__X, ____XXXX,
  X__X____, ________, XXXXXXXX, ____XXXX, XXXX____, XXXX____, ____XXXX, XXXXXXXX,
  ________, XXXXX__X, _____XX_, XXXXX__X, _____XX_, XXXXX___, _____XXX, X__X___X,
  _XX_XXX_, XXXXXX__, ______XX, ______XX, XXXXXX__, XXXX____, ____XXXX, ________,
  XXXXXXXX, XXXX____, ____X__X, ________, X__XX__X, XXXX____, ____XXXX, ________,
  XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXX____,
};


const map_goto_entry_t stage6_map_goto_table[6] = {
  { STAGE6_MAP_START_CURVATURE_ADDR, &stage6_map_start_curvature[0] },
  { STAGE6_MAP_START_HEIGHT_ADDR,    &stage6_map_start_height[0]    },
  { STAGE6_MAP_START_LANES_ADDR,     &stage6_map_start_lanes[0]     },
  { STAGE6_MAP_START_HAZARDS_ADDR,   &stage6_map_start_hazards[0]   },
  { STAGE6_MAP_START_LEFTOBJS_ADDR,  &stage6_map_start_leftobjs[0]  },
  { STAGE6_MAP_START_RIGHTOBJS_ADDR, &stage6_map_start_rightobjs[0] },
};

// clang-format on
