#!/usr/bin/env python3
"""Report where the bytes go in the linked ChaseHQ executable.

Runs off the linker's own map file, so every byte in the binary is
attributed to the object file and symbol that produced it.  With --z80 the
report is set against the original Z80 sizes taken from the skool files, which
answers the interesting question: how much did each routine grow when it became
AArch64, and how much of the port is data that did not grow at all.

Usage:
    scripts/size_report.py [build-dir] [--z80] [--top N] [--csv FILE]

The build directory defaults to the first of cmake-build-minsizerel,
cmake-build-release, cmake-build-relwithdebinfo, cmake-build-debug that exists.
A map file is generated by re-running the link command ninja already knows,
with -Wl,-map added.
"""

import argparse
import csv
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CROOT = os.path.dirname(HERE)
SPECCY = os.path.join(os.path.dirname(CROOT), "Speccy")

BUILD_DIR_PREFERENCE = [
    "cmake-build-minsizerel",
    "cmake-build-release",
    "cmake-build-relwithdebinfo",
    "cmake-build-debug",
]

# A ZX Spectrum 128K: 8 x 16K banks.
ORIGINAL_TOTAL = 128 * 1024

# Sections that hold executable code, read-only data, writable data.  Anything
# else (unwind tables, pointer fixups, the load commands) lands in "other".
CODE_SECTIONS = {"__text", "__stubs", "__stub_helper", "__auth_stubs"}
RODATA_SECTIONS = {"__const", "__cstring", "__literal8", "__literal16", "__cfstring"}
DATA_SECTIONS = {"__data", "__common", "__bss", "__got", "__auth_got", "__la_symbol_ptr"}


# ---------------------------------------------------------------- map parsing


class MapFile(object):
    """The three tables in an Apple ld map: objects, sections, symbols."""

    def __init__(self, path):
        self.objects = {}  # index -> object path
        self.sections = []  # (address, size, segment, section)
        self.symbols = []  # (address, size, object index, name)
        self._parse(path)

    def _parse(self, path):
        obj_re = re.compile(r"^\[\s*(\d+)\]\s+(.*)$")
        sec_re = re.compile(r"^(0x[0-9A-Fa-f]+)\t(0x[0-9A-Fa-f]+)\t(\S+)\t(\S+)$")
        sym_re = re.compile(r"^(0x[0-9A-Fa-f]+)\t(0x[0-9A-Fa-f]+)\t\[\s*(\d+)\]\s+(.*)$")
        with open(path, errors="replace") as handle:
            for line in handle:
                line = line.rstrip("\n")
                match = sym_re.match(line)
                if match:
                    self.symbols.append(
                        (
                            int(match.group(1), 16),
                            int(match.group(2), 16),
                            int(match.group(3)),
                            match.group(4),
                        )
                    )
                    continue
                match = sec_re.match(line)
                if match:
                    self.sections.append(
                        (
                            int(match.group(1), 16),
                            int(match.group(2), 16),
                            match.group(3),
                            match.group(4),
                        )
                    )
                    continue
                match = obj_re.match(line)
                if match:
                    self.objects[int(match.group(1))] = match.group(2)
        self.sections.sort()

    def section_of(self, address):
        """Which (segment, section) an address falls in, or (?, ?)."""
        for start, size, segment, section in self.sections:
            if start <= address < start + size:
                return segment, section
        return "?", "?"


def ensure_map(build):
    """Return the path to a map file for build/ChaseHQ, relinking if needed."""
    binary = os.path.join(build, "ChaseHQ")
    mapfile = os.path.join(build, "ChaseHQ.map")
    if not os.path.exists(binary):
        sys.exit("no ChaseHQ binary in %s - build it first" % build)
    if os.path.exists(mapfile) and os.path.getmtime(mapfile) >= os.path.getmtime(binary):
        return mapfile
    link = subprocess.check_output(
        ["ninja", "-t", "commands", "ChaseHQ"], cwd=build
    ).decode()
    link = link.strip().split("\n")[-1]
    if " -o ChaseHQ " not in link:
        sys.exit("cannot find the link step in ninja's command list")
    link = link.replace(" -o ChaseHQ ", " -Wl,-map,ChaseHQ.map -o ChaseHQ ")
    subprocess.check_call(link, shell=True, cwd=build)
    return mapfile


# -------------------------------------------------------------- attribution


def component_of(objpath):
    """Group an object file into one of the buckets the report is built on."""
    if "/ChaseHQ/Engine/" in objpath:
        return "game code (Engine)"
    if "/ChaseHQ/Data/" in objpath:
        return "game data (Data)"
    if "/ZXSpectrum/" in objpath:
        return "ZX facade"
    if "/apps/" in objpath:
        return "host app (SDL3)"
    if objpath == "linker synthesized":
        return "linker"
    return "external"


def bucket_of(section):
    if section in CODE_SECTIONS:
        return "code"
    if section in RODATA_SECTIONS:
        return "rodata"
    if section in DATA_SECTIONS:
        return "data"
    return "other"


def tally(mapfile):
    """Sum symbol sizes per (component, object, bucket)."""
    by_component = {}
    by_object = {}
    for address, size, index, name in mapfile.symbols:
        if size == 0:
            continue
        objpath = mapfile.objects.get(index, "?")
        segment, section = mapfile.section_of(address)
        bucket = bucket_of(section)
        component = component_of(objpath)
        by_component.setdefault(component, {}).setdefault(bucket, 0)
        by_component[component][bucket] += size
        by_object.setdefault(objpath, {}).setdefault(bucket, 0)
        by_object[objpath][bucket] += size
    return by_component, by_object


# ------------------------------------------------------------ skool parsing

ENTRY_RE = re.compile(r"^([a-z])\$([0-9A-Fa-f]{4})")
INSTR_RE = re.compile(r"^[ *]\$([0-9A-Fa-f]{4})")
LABEL_RE = re.compile(r"^@label=(\S+)")

# Skool entry types: c is code, everything else is data of one kind or another.
ENTRY_KIND = {
    "c": "code",
    "b": "data",
    "t": "text",
    "w": "words",
    "g": "state",
    "s": "zeros",
    "u": "unused",
}


def parse_skool(path):
    """Return a list of (start, end, kind, label) for every entry in a skool."""
    entries = []
    pending_label = None
    with open(path, errors="replace") as handle:
        for line in handle:
            match = LABEL_RE.match(line)
            if match:
                pending_label = match.group(1)
                continue
            match = ENTRY_RE.match(line)
            if match:
                entries.append(
                    [int(match.group(2), 16), None, ENTRY_KIND.get(match.group(1), "?"),
                     pending_label]
                )
                pending_label = None
                continue
            if INSTR_RE.match(line):
                pending_label = None
    # An entry runs up to the start of the next one.  The final entry in a file
    # has no successor, so it is left with no size and dropped from the totals.
    for index in range(len(entries) - 1):
        entries[index][1] = entries[index + 1][0]
    return [tuple(entry) for entry in entries if entry[1] is not None]


def load_skools():
    entries = []
    if not os.path.isdir(SPECCY):
        sys.exit("no skool directory at %s" % SPECCY)
    for name in sorted(os.listdir(SPECCY)):
        if name.endswith(".skool"):
            entries += parse_skool(os.path.join(SPECCY, name))
    return entries


# ---------------------------------------------------------------- reporting


def clip(text, width=56):
    """Trim a name to keep the tables readable.  String literals appear in the
    map as pseudo-symbols carrying their whole contents, which can be huge."""
    text = " ".join(text.split())
    if len(text) > width:
        return text[: width - 3] + "..."
    return text


def human(value):
    if value >= 1024:
        return "%d (%.1fK)" % (value, value / 1024.0)
    return "%d" % value


def table(title, rows, columns):
    """Print rows as a fixed-width table, widest column value setting width."""
    print("")
    print("=== %s ===" % title)
    widths = [len(column) for column in columns]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(str(cell)))
    line = "%-*s" % (widths[0], columns[0])
    line += "  " + "  ".join(
        "%*s" % (widths[index], columns[index]) for index in range(1, len(columns))
    )
    print(line)
    print("-" * len(line))
    for row in rows:
        line = "%-*s" % (widths[0], row[0])
        line += "  " + "  ".join(
            "%*s" % (widths[index], row[index]) for index in range(1, len(row))
        )
        print(line)


def bucket_row(name, buckets):
    total = sum(buckets.values())
    return (
        name,
        buckets.get("code", 0),
        buckets.get("rodata", 0),
        buckets.get("data", 0),
        buckets.get("other", 0),
        total,
    )


def report_sections(mapfile):
    rows = []
    for _, size, segment, section in mapfile.sections:
        rows.append(("%s,%s" % (segment, section), human(size), bucket_of(section)))
    total = sum(size for _, size, _, _ in mapfile.sections)
    rows.append(("TOTAL", human(total), ""))
    table("Sections in the linked binary", rows, ("segment,section", "size", "bucket"))
    return total


def report_components(by_component):
    order = sorted(by_component, key=lambda key: -sum(by_component[key].values()))
    rows = [bucket_row(name, by_component[name]) for name in order]
    grand = {}
    for buckets in by_component.values():
        for bucket, size in buckets.items():
            grand[bucket] = grand.get(bucket, 0) + size
    rows.append(bucket_row("TOTAL", grand))
    table("By component", rows, ("component", "code", "rodata", "data", "other", "total"))


def report_objects(by_object):
    order = sorted(by_object, key=lambda key: -sum(by_object[key].values()))
    rows = []
    for objpath in order:
        name = objpath.replace("CMakeFiles/ChaseHQ.dir/", "")
        if len(name) > 52:
            name = "..." + name[-49:]
        rows.append(bucket_row(name, by_object[objpath]))
    table("By object file", rows, ("object", "code", "rodata", "data", "other", "total"))


def report_top(mapfile, count):
    rows = []
    for address, size, index, name in sorted(
        mapfile.symbols, key=lambda symbol: -symbol[1]
    )[:count]:
        objpath = mapfile.objects.get(index, "?")
        _, section = mapfile.section_of(address)
        rows.append(
            (clip(name.lstrip("_")), size, section, os.path.basename(objpath))
        )
    table("Largest %d symbols" % count, rows, ("symbol", "size", "section", "object"))


def report_baseline(by_component, skool_entries):
    """Set the port's game bytes against the original's, and explain the gap."""
    game = {}
    for component in ("game code (Engine)", "game data (Data)", "ZX facade"):
        for bucket, size in by_component.get(component, {}).items():
            game[bucket] = game.get(bucket, 0) + size
    host = sum(
        sum(by_component.get(component, {}).values())
        for component in ("host app (SDL3)", "external", "linker")
    )
    rows = [
        ("original 128K image", human(ORIGINAL_TOTAL)),
        ("port: game code", human(game.get("code", 0))),
        ("port: game read-only data", human(game.get("rodata", 0))),
        ("port: game writable data", human(game.get("data", 0))),
        ("port: game total", human(sum(game.values()))),
        ("port: host and libraries", human(host)),
    ]
    if skool_entries:
        z80 = {}
        for start, end, kind, _ in skool_entries:
            z80[kind] = z80.get(kind, 0) + (end - start)
        z80_code = z80.get("code", 0)
        z80_data = sum(
            size for kind, size in z80.items() if kind not in ("code", "unused")
        )
        rows.append(("original: Z80 code bytes", human(z80_code)))
        for kind in sorted(z80, key=lambda key: -z80[key]):
            if kind != "code":
                rows.append(("original: Z80 %s bytes" % kind, human(z80[kind])))
        rows.append(("original: Z80 data bytes (less unused)", human(z80_data)))
        if z80_code:
            rows.append(
                ("code expansion", "%.1fx" % (game.get("code", 0) / float(z80_code)))
            )
        if z80_data:
            rows.append(
                (
                    "data expansion",
                    "%.1fx" % (game.get("rodata", 0) / float(z80_data)),
                )
            )
    table("Against the original", rows, ("measure", "bytes"))


def report_expansion(mapfile, skool_entries, count):
    """Per-routine Z80 versus AArch64 sizes, matched on the skool label."""
    z80_sizes = {}
    for start, end, kind, label in skool_entries:
        if kind == "code" and label:
            z80_sizes[label] = z80_sizes.get(label, 0) + (end - start)
    rows = []
    matched_arm = 0
    matched_z80 = 0
    unmatched = []
    for address, size, index, name in mapfile.symbols:
        objpath = mapfile.objects.get(index, "?")
        if component_of(objpath) != "game code (Engine)":
            continue
        _, section = mapfile.section_of(address)
        if section != "__text" or size == 0:
            continue
        plain = name.lstrip("_")
        if plain in z80_sizes:
            z80 = z80_sizes[plain]
            matched_arm += size
            matched_z80 += z80
            rows.append((plain, z80, size, "%.1fx" % (size / float(z80))))
        else:
            unmatched.append((plain, size))
    rows.sort(key=lambda row: -row[2])
    table(
        "Biggest %d routines by AArch64 size (matched to skool label)" % count,
        rows[:count],
        ("routine", "z80", "arm64", "ratio"),
    )
    print("")
    print(
        "matched %d routines: %s Z80 -> %s AArch64 (%.1fx)"
        % (
            len(rows),
            human(matched_z80),
            human(matched_arm),
            matched_arm / float(matched_z80) if matched_z80 else 0.0,
        )
    )
    unmatched.sort(key=lambda row: -row[1])
    print(
        "unmatched (no skool label of that name): %d symbols, %s"
        % (len(unmatched), human(sum(size for _, size in unmatched)))
    )
    if unmatched:
        print("  largest: " + ", ".join(
            "%s (%d)" % (name, size) for name, size in unmatched[:8]
        ))
    return rows


def write_csv(path, mapfile):
    with open(path, "w") as handle:
        writer = csv.writer(handle)
        writer.writerow(("symbol", "size", "segment", "section", "bucket",
                         "object", "component"))
        for address, size, index, name in mapfile.symbols:
            objpath = mapfile.objects.get(index, "?")
            segment, section = mapfile.section_of(address)
            writer.writerow((name.lstrip("_"), size, segment, section,
                             bucket_of(section), objpath, component_of(objpath)))
    print("")
    print("per-symbol CSV written to %s" % path)


def self_check():
    """Exercise both parsers on synthetic input; the report is only as good."""
    import tempfile

    mapdata = (
        "# Path: /tmp/x\n"
        "# Object files:\n"
        "[  0] linker synthesized\n"
        "[  1] CMakeFiles/ChaseHQ.dir/libraries/ChaseHQ/Engine/Main.c.o\n"
        "# Sections:\n"
        "# Address\tSize    \tSegment\tSection\n"
        "0x100001000\t0x00000100\t__TEXT\t__text\n"
        "0x100001100\t0x00000080\t__TEXT\t__const\n"
        "# Symbols:\n"
        "# Address\tSize    \tFile  Name\n"
        "0x100001000\t0x00000040\t[  1] _draw_road\n"
        "0x100001100\t0x00000080\t[  1] _some_table\n"
    )
    skooldata = (
        "@label=draw_road\n"
        "c$C000 LD A,B\n"
        " $C001 RET\n"
        "\n"
        "b$C010 DEFB $00\n"
        "\n"
        "c$C020 NOP\n"
    )
    handle = tempfile.NamedTemporaryFile("w", suffix=".map", delete=False)
    handle.write(mapdata)
    handle.close()
    mapfile = MapFile(handle.name)
    os.unlink(handle.name)
    assert mapfile.objects[1].endswith("Main.c.o"), mapfile.objects
    assert mapfile.section_of(0x100001000) == ("__TEXT", "__text")
    assert mapfile.section_of(0x100001100) == ("__TEXT", "__const")
    by_component, _ = tally(mapfile)
    assert by_component["game code (Engine)"] == {"code": 0x40, "rodata": 0x80}, \
        by_component

    handle = tempfile.NamedTemporaryFile("w", suffix=".skool", delete=False)
    handle.write(skooldata)
    handle.close()
    entries = parse_skool(handle.name)
    os.unlink(handle.name)
    # The final entry has no successor, so only the first two are sized.
    assert entries == [(0xC000, 0xC010, "code", "draw_road"),
                       (0xC010, 0xC020, "data", None)], entries
    print("self-check passed")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("build", nargs="?", help="CMake build directory")
    parser.add_argument("--z80", action="store_true",
                        help="compare against the skool disassembly")
    parser.add_argument("--top", type=int, default=25, help="rows in top-N tables")
    parser.add_argument("--csv", help="write the full per-symbol table here")
    parser.add_argument("--self-check", action="store_true",
                        help="run the parser self-check and exit")
    args = parser.parse_args()

    if args.self_check:
        self_check()
        return

    build = args.build
    if not build:
        for candidate in BUILD_DIR_PREFERENCE:
            if os.path.exists(os.path.join(CROOT, candidate, "ChaseHQ")):
                build = os.path.join(CROOT, candidate)
                break
    if not build:
        sys.exit("no build directory found - configure and build first")
    build = os.path.abspath(build)

    mapfile = MapFile(ensure_map(build))
    by_component, by_object = tally(mapfile)
    skool_entries = load_skools() if args.z80 else []

    print("build: %s" % build)
    total = report_sections(mapfile)
    report_components(by_component)
    report_objects(by_object)
    report_top(mapfile, args.top)
    report_baseline(by_component, skool_entries)
    if args.z80:
        report_expansion(mapfile, skool_entries, args.top)
    if args.csv:
        write_csv(args.csv, mapfile)
    print("")
    print("section total %s; symbols attributed %s"
          % (human(total),
             human(sum(size for _, size, _, _ in mapfile.symbols))))


if __name__ == "__main__":
    main()
