# Script-mode helper: embeds a compiled SPIR-V binary as a C byte array.
# Usage: cmake -DINPUT=<spv file> -DOUTPUT=<header file> -DVARNAME=<c name> -P EmbedSPIRV.cmake

file(READ "${INPUT}" hex_data HEX)
string(LENGTH "${hex_data}" hex_len)
math(EXPR byte_count "${hex_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex_array "${hex_data}")

file(WRITE "${OUTPUT}" "/* Generated by EmbedSPIRV.cmake from ${INPUT}. Do not edit. */\n")
file(APPEND "${OUTPUT}" "static const unsigned char ${VARNAME}[] = {\n${hex_array}\n};\n")
file(APPEND "${OUTPUT}" "static const unsigned int ${VARNAME}_len = ${byte_count}u;\n")
