on:
  push:
    branches: develop
    paths:
      - 'Speccy/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: develop
    paths:
      - 'Speccy/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Speccy
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Install SkoolKit
      run: pip install 'skoolkit>=9.0'

    - name: Build the disassembly
      run: make all
